import express from "express";
import connectDB from "./admindb.js";
// import students from "./students.js";

import teachers from "./teachers.js";
import library from "./library.js";
// import timetable from "./timetable.js";
import upcommingexams from "./upcommingexams.js";
import gallery from "./gallery.js";
import gallerypage from "./gallerypage.js";
import event from "./event.js";
// import bustrack from "./bustrack.js";
// import trackbus from "./trackbus.js";
import attendance from "./attendance.js";
import schedule from "./schedule.js";
import examresult from "./examresult.js";
import subject from "./subject.js";
import first from "./first.js";
import second from "./second.js";
import third from "./third.js";
import fourth from "./fourth.js";
import fifth from "./fifth.js";
import sixth from "./sixth.js";
import seven from "./seven.js";
import eight from "./eight.js";
import ninth from "./ninth.js";
import ten from "./ten.js";
import eleventh from "./eleventh.js";
import twelfth from "./twelfth.js";
import teacherstimetable from "./teacherstimetable.js";
import firsttimetable from "./firsttimetable.js";
import secondtimetable from "./secondtimetable.js";
import thirdtimetable from "./thirdtimetable.js";
import fourthtimetable from "./fourthtimetable.js";
import fifthtimetable from "./fifthtimetable.js";
import sixthtimetable from "./sixthtimetable.js";
import seventimetable from "./seventimetable.js";
import eighttimetable from "./eighthtimetable.js";
import ninthtimetable from "./ninthtimetable.js";
import tenthtimetable from "./tenthtimetable.js";
import eleventhtimetable from "./eleventhtimetable.js";
import twelfthtimetable from "./twelfthtimetable.js";
connectDB()

const app=express();
app.use(express.json());
// app.use('/students',students);
// app.use('/first',first);
app.use('/teachers',teachers);
app.use('/library',library);
// app.use('/timetable',timetable);
app.use('/upcommingexams',upcommingexams);
app.use('/examresult',examresult);
app.use('/gallery',gallery);
app.use('/gallerypage',gallerypage);
app.use('/event',event);
// app.use('/bustrack',bustrack);
// app.use('/trackbus',trackbus);
app.use('/attendance',attendance);
app.use('/schedule',schedule);

app.use('/subject',subject);
app.use('/first',first);
app.use('/second',second);
app.use('/third',third);
app.use('/fourth',fourth);
app.use('/fifth',fifth);
app.use('/sixth',sixth);
app.use('/seven',seven);
app.use('/eight',eight);
app.use('/ninth',ninth);
app.use('/ten',ten);
app.use('/eleventh',eleventh);
app.use('/twelfth',twelfth);
app.use('/teacherstimetable',teacherstimetable);
app.use('/firsttimetable',firsttimetable);
app.use('/secondtimetable',secondtimetable);
app.use('/thirdtimetable',thirdtimetable);
app.use('/fourthtimetable',fourthtimetable);
app.use('/fifthtimetable',fifthtimetable);
app.use('/sixthtimetable',sixthtimetable);
app.use('/seventimetable',seventimetable);
app.use('/eighttimetable',eighttimetable);
app.use('/ninthtimetable',ninthtimetable);
app.use('/tenthtimetable',tenthtimetable);
app.use('/eleventhtimetable',eleventhtimetable);
app.use('/twelfthtimetable',twelfthtimetable);
const port=5000;
app.listen(port,()=>{
    console.log(`server is running at ${port}`);
 
});
